### ISSUE TITLE
Example doesn't work, v. 0.1.9 doesn't exist

### ISSUE THREAD

**Issue by Michae1Nechaev** [FreshworksStudio/arcorelocation#4]
I try to run example but picture freezes and stops. 
I also try to run project with pod  v. 0.1.9 but CocoaPods could not find compatible versions for pod "ARCoreLocation":
  In Podfile:
    ARCoreLocation (~> 0.1.9)
Hope on your reply!

**Comment by ghost** [comment]
Hi! Can you include your podfile?
The example looks like this, and the pod installs successfully when running `pod install`

```
target 'ARCoreLocationExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARCoreLocationExample

  # AR + CoreLocation
  pod 'ARCoreLocation', '~> 0.1.9'

end
```

**Comment by Michae1Nechaev** [comment]
Ok, but example project freezes screen

**Comment by ghost** [comment]
Ok. More details would be helpful. ARKit requires certain hardware. What iOS version are you running, and on what device? Also note that ARKit does not function in an iOS simulator.

**Comment by Michae1Nechaev** [comment]
I  use iPhone SE with iOS 13.3 for running

**Comment by Michae1Nechaev** [comment]
Example app crashes in ListLandmarksVC 84 line while force unwrapping location

**Comment by smithskyler** [comment]
I see. Thanks for pointing that out. I had updated the example with some new functionality, but hadn't checked that it worked when installing from scratch. I've now created a new version with a "ready" method in the `ARLandmarkerDelegate` that should fix your problem.

The problem was just that the example required location and camera permissions to be enabled at launch, which would never be the case on the first launch.

**Comment by Michae1Nechaev** [comment]
Sure, thank you
But unfortunately I can't see any landmarks on screen. Is it that I'm on the other side of the planet?

**Comment by smithskyler** [comment]
Yes, that's because the settings only show landmarks within 100 metres of the device. You can change that configuration in `ListLandmarksViewController` `viewDidLoad`. Specifically, you should change line 39, `landmarker.maximumVisibleDistance = 100`. If you remove that line, you will see a stack of landmarks. If you want to see landmarks close to you, edit `Mountain.swift`. The landmarks that are currently showing are `VictoriaData_Landmarks`. You can create your own landmark data to show in the app.
